-------------------------------------------------
--  Utilities for casting trust spells
-------------------------------------------------

require("scripts/globals/status")
require("scripts/globals/msg")

possibleBuffTargets = {
    PLAYER = 1,
    CASTER = 2,
    PARTY = 4
}

local magicGroupIndex = {
    dsp.magic.PROTECTRA,
    dsp.magic.PROTECTRA_II,
    dsp.magic.PROTECTRA_III,
    dsp.magic.PROTECTRA_IV,
    dsp.magic.PROTECTRA_V,
    dsp.magic.SHELLRA,
    dsp.magic.SHELLRA_II,
    dsp.magic.SHELLRA_III,
    dsp.magic.SHELLRA_IV,
    dsp.magic.SHELLRA_V,
    dsp.magic.BARAMNESRA,
    dsp.magic.BARSLEEPRA,
    dsp.magic.BARPOISONRA,
    dsp.magic.BARPARALYZRA,
    dsp.magic.BARBLINDRA,
    dsp.magic.BARSILENCERA,
    dsp.magic.BARPETRA,
    dsp.magic.BARVIRA,
}

local magicSingleTierIndex = {
    [5] = { dsp.magic.AERO_V, dsp.magic.FIRE_V, dsp.magic.STONE_V, dsp.magic.WATER_V, dsp.magic.BLIZZARD_V, dsp.magic.THUNDER_V },
    [4] = { dsp.magic.AERO_IV, dsp.magic.FIRE_IV, dsp.magic.STONE_IV, dsp.magic.WATER_IV, dsp.magic.BLIZZARD_IV, dsp.magic.THUNDER_IV },
    [3] = { dsp.magic.AERO_III, dsp.magic.FIRE_III, dsp.magic.STONE_III, dsp.magic.WATER_III, dsp.magic.BLIZZARD_III, dsp.magic.THUNDER_III },
    [2] = { dsp.magic.AERO_II, dsp.magic.FIRE_II, dsp.magic.STONE_II, dsp.magic.WATER_II, dsp.magic.BLIZZARD_II, dsp.magic.THUNDER_II },
    [1] = { dsp.magic.AERO, dsp.magic.FIRE, dsp.magic.STONE, dsp.magic.WATER, dsp.magic.BLIZZARD, dsp.magic.THUNDER },
}

-- spell name, mana required
local magicIndex = {
    [dsp.magic.CURE] = 8,
    [dsp.magic.CURE_II] = 24,
    [dsp.magic.CURE_III] = 46,
    [dsp.magic.CURE_IV] = 88,
    [dsp.magic.CURE_V] = 135,
    [dsp.magic.CURE_VI] = 227,
    [dsp.magic.CURAGA] = 60,
    [dsp.magic.CURAGA_II] = 120,
    [dsp.magic.CURAGA_III] = 180,
    [dsp.magic.CURAGA_IV] = 260,
    [dsp.magic.CURAGA_V] = 380,
    [dsp.magic.RAISE] = 150,
    [dsp.magic.RAISE_II] = 150,
    [dsp.magic.POISONA] = 8,
    [dsp.magic.PARALYNA] = 12,
    [dsp.magic.BLINDNA] = 16,
    [dsp.magic.SILENA] = 24,
    [dsp.magic.STONA] = 40,
    [dsp.magic.VIRUNA] = 48,
    [dsp.magic.CURSNA] = 30,
    [dsp.magic.HOLY] = 100,
    [dsp.magic.HOLY_II] = 150,
    [dsp.magic.DIA] = 7,
    [dsp.magic.DIA_II] = 30,
    [dsp.magic.DIA_III] = 45,
    [dsp.magic.DIA_IV] = 164,
    [dsp.magic.DIA_V] = 217,
    [dsp.magic.BANISH] = 15,
    [dsp.magic.BANISH_II] = 57,
    [dsp.magic.BANISH_III] = 96,
    [dsp.magic.BANISH_IV] = 108,
    [dsp.magic.BANISH_V] = 159,
    [dsp.magic.DIAGA] = 12,
    [dsp.magic.DIAGA_II] = 60,
    [dsp.magic.DIAGA_III] = 120,
    [dsp.magic.DIAGA_IV] = 180,
    [dsp.magic.DIAGA_V] = 240,
    [dsp.magic.BANISHGA] = 41,
    [dsp.magic.BANISHGA_II] = 120,
    [dsp.magic.BANISHGA_III] = 233,
    [dsp.magic.BANISHGA_IV] = 380,
    [dsp.magic.BANISHGA_V] = 563,
    [dsp.magic.PROTECT] = 9,
    [dsp.magic.PROTECT_II] = 28,
    [dsp.magic.PROTECT_III] = 46,
    [dsp.magic.PROTECT_IV] = 65,
    [dsp.magic.PROTECT_V] = 84,
    [dsp.magic.SHELL] = 18,
    [dsp.magic.SHELL_II] = 37,
    [dsp.magic.SHELL_III] = 56,
    [dsp.magic.SHELL_IV] = 75,
    [dsp.magic.SHELL_V] = 93,
    [dsp.magic.BLINK] = 20,
    [dsp.magic.STONESKIN] = 29,
    [dsp.magic.AQUAVEIL] = 12,
    [dsp.magic.SLOW] = 15,
    [dsp.magic.HASTE] = 40,
    [dsp.magic.PARALYZE] = 6,
    [dsp.magic.SILENCE] = 16,
    [dsp.magic.BARFIRE] = 6,
    [dsp.magic.BARBLIZZARD] = 6,
    [dsp.magic.BARAERO] = 6,
    [dsp.magic.BARSTONE] = 6,
    [dsp.magic.BARTHUNDER] = 6,
    [dsp.magic.BARWATER] = 6,
    [dsp.magic.BARFIRA] = 12,
    [dsp.magic.BARBLIZZARA] = 12,
    [dsp.magic.BARAERA] = 12,
    [dsp.magic.BARSTONRA] = 12,
    [dsp.magic.BARTHUNDRA] = 12,
    [dsp.magic.BARWATERA] = 12,
    [dsp.magic.BARSLEEP] = 7,
    [dsp.magic.BARPOISON] = 9,
    [dsp.magic.BARPARALYZE] = 11,
    [dsp.magic.BARBLIND] = 13,
    [dsp.magic.BARSILENCE] = 15,
    [dsp.magic.BARPETRIFY] = 20,
    [dsp.magic.BARVIRUS] = 25,
    [dsp.magic.SLOW_II] = 45,
    [dsp.magic.PARALYZE_II] = 36,
    [dsp.magic.RECALL_JUGNER] = 125,
    [dsp.magic.RECALL_PASHH] = 125,
    [dsp.magic.RECALL_MERIPH] = 125,
    [dsp.magic.BARAMNESIA] = 30,
    [dsp.magic.BARAMNESRA] = 60,
    [dsp.magic.BARSLEEPRA] = 14,
    [dsp.magic.BARPOISONRA] = 18,
    [dsp.magic.BARPARALYZRA] = 22,
    [dsp.magic.BARBLINDRA] = 26,
    [dsp.magic.BARSILENCERA] = 30,
    [dsp.magic.BARPETRA] = 40,
    [dsp.magic.BARVIRA] = 50,
    [dsp.magic.CURA] = 30,
    [dsp.magic.SACRIFICE] = 18,
    [dsp.magic.ESUNA] = 24,
    [dsp.magic.AUSPICE] = 30,
    [dsp.magic.REPRISAL] = 24,
    [dsp.magic.REPOSE] = 26,
    [dsp.magic.SANDSTORM] = 30,
    [dsp.magic.ENFIRE] = 12,
    [dsp.magic.ENBLIZZARD] = 12,
    [dsp.magic.ENAERO] = 12,
    [dsp.magic.ENSTONE] = 12,
    [dsp.magic.ENTHUNDER] = 12,
    [dsp.magic.ENWATER] = 12,
    [dsp.magic.PHALANX] = 21,
    [dsp.magic.PHALANX_II] = 42,
    [dsp.magic.REGEN] = 15,
    [dsp.magic.REFRESH] = 40,
    [dsp.magic.REGEN_II] = 36,
    [dsp.magic.REGEN_III] = 64,
    [dsp.magic.FLASH] = 25,
    [dsp.magic.RAINSTORM] = 30,
    [dsp.magic.WINDSTORM] = 30,
    [dsp.magic.FIRESTORM] = 30,
    [dsp.magic.HAILSTORM] = 30,
    [dsp.magic.THUNDERSTORM] = 30,
    [dsp.magic.VOIDSTORM] = 30,
    [dsp.magic.AURORASTORM] = 30,
    [dsp.magic.TELEPORT_YHOAT] = 100,
    [dsp.magic.TELEPORT_ALTEP] = 100,
    [dsp.magic.TELEPORT_HOLLA] = 75,
    [dsp.magic.TELEPORT_DEM] = 75,
    [dsp.magic.TELEPORT_MEA] = 75,
    [dsp.magic.PROTECTRA] = 9,
    [dsp.magic.PROTECTRA_II] = 28,
    [dsp.magic.PROTECTRA_III] = 46,
    [dsp.magic.PROTECTRA_IV] = 65,
    [dsp.magic.PROTECTRA_V] = 84,
    [dsp.magic.SHELLRA] = 18,
    [dsp.magic.SHELLRA_II] = 37,
    [dsp.magic.SHELLRA_III] = 56,
    [dsp.magic.SHELLRA_IV] = 75,
    [dsp.magic.SHELLRA_V] = 93,
    [dsp.magic.RERAISE] = 150,
    [dsp.magic.INVISIBLE] = 15,
    [dsp.magic.SNEAK] = 12,
    [dsp.magic.DEODORIZE] = 10,
    [dsp.magic.TELEPORT_VAHZL] = 100,
    [dsp.magic.RAISE_III] = 150,
    [dsp.magic.RERAISE_II] = 150,
    [dsp.magic.RERAISE_III] = 150,
    [dsp.magic.ERASE] = 18,
    [dsp.magic.FIRE] = 7,
    [dsp.magic.FIRE_II] = 26,
    [dsp.magic.FIRE_III] = 63,
    [dsp.magic.FIRE_IV] = 135,
    [dsp.magic.FIRE_V] = 228,
    [dsp.magic.BLIZZARD] = 8,
    [dsp.magic.BLIZZARD_II] = 31,
    [dsp.magic.BLIZZARD_III] = 75,
    [dsp.magic.BLIZZARD_IV] = 162,
    [dsp.magic.BLIZZARD_V] = 267,
    [dsp.magic.AERO] = 6,
    [dsp.magic.AERO_II] = 22,
    [dsp.magic.AERO_III] = 54,
    [dsp.magic.AERO_IV] = 115,
    [dsp.magic.AERO_V] = 198,
    [dsp.magic.STONE] = 4,
    [dsp.magic.STONE_II] = 16,
    [dsp.magic.STONE_III] = 40,
    [dsp.magic.STONE_IV] = 88,
    [dsp.magic.STONE_V] = 156,
    [dsp.magic.THUNDER] = 9,
    [dsp.magic.THUNDER_II] = 37,
    [dsp.magic.THUNDER_III] = 91,
    [dsp.magic.THUNDER_IV] = 195,
    [dsp.magic.THUNDER_V] = 306,
    [dsp.magic.WATER] = 5,
    [dsp.magic.WATER_II] = 19,
    [dsp.magic.WATER_III] = 46,
    [dsp.magic.WATER_IV] = 99,
    [dsp.magic.WATER_V] = 175,
    [dsp.magic.FIRAGA] = 57,
    [dsp.magic.FIRAGA_II] = 153,
    [dsp.magic.FIRAGA_III] = 263,
    [dsp.magic.FIRAGA_IV] = 428,
    [dsp.magic.FIRAGA_V] = 610,
    [dsp.magic.BLIZZAGA] = 80,
    [dsp.magic.BLIZZAGA_II] = 175,
    [dsp.magic.BLIZZAGA_III] = 297,
    [dsp.magic.BLIZZAGA_IV] = 455,
    [dsp.magic.BLIZZAGA_V] = 642,
    [dsp.magic.AEROGA] = 45,
    [dsp.magic.AEROGA_II] = 131,
    [dsp.magic.AEROGA_III] = 232,
    [dsp.magic.AEROGA_IV] = 396,
    [dsp.magic.AEROGA_V] = 571,
    [dsp.magic.STONEGA] = 24,
    [dsp.magic.STONEGA_II] = 93,
    [dsp.magic.STONEGA_III] = 175,
    [dsp.magic.STONEGA_IV] = 345,
    [dsp.magic.STONEGA_V] = 512,
    [dsp.magic.THUNDAGA] = 105,
    [dsp.magic.THUNDAGA_II] = 200,
    [dsp.magic.THUNDAGA_III] = 332,
    [dsp.magic.THUNDAGA_IV] = 483,
    [dsp.magic.THUNDAGA_V] = 674,
    [dsp.magic.WATERGA] = 34,
    [dsp.magic.WATERGA_II] = 112,
    [dsp.magic.WATERGA_III] = 202,
    [dsp.magic.WATERGA_IV] = 371,
    [dsp.magic.WATERGA_V] = 541,
    [dsp.magic.FLARE] = 315,
    [dsp.magic.FLARE_II] = 280,
    [dsp.magic.FREEZE] = 315,
    [dsp.magic.FREEZE_II] = 280,
    [dsp.magic.TORNADO] = 315,
    [dsp.magic.TORNADO_II] = 280,
    [dsp.magic.QUAKE] = 315,
    [dsp.magic.QUAKE_II] = 280,
    [dsp.magic.BURST] = 315,
    [dsp.magic.BURST_II] = 280,
    [dsp.magic.FLOOD] = 315,
    [dsp.magic.FLOOD_II] = 280,
    [dsp.magic.GRAVITY] = 24,
    [dsp.magic.GRAVITY_II] = 36,
    [dsp.magic.METEOR] = 418,
    [dsp.magic.COMET] = 350,
    [dsp.magic.POISON] = 5,
    [dsp.magic.POISON_II] = 38,
    [dsp.magic.POISON_III] = 72,
    [dsp.magic.POISON_IV] = 106,
    [dsp.magic.POISON_V] = 140,
    [dsp.magic.POISONGA] = 44,
    [dsp.magic.POISONGA_II] = 112,
    [dsp.magic.POISONGA_III] = 180,
    [dsp.magic.POISONGA_IV] = 248,
    [dsp.magic.POISONGA_V] = 314,
    [dsp.magic.BIO] = 15,
    [dsp.magic.BIO_II] = 36,
    [dsp.magic.BIO_III] = 54,
    [dsp.magic.BIO_IV] = 154,
    [dsp.magic.BIO_V] = 197,
    [dsp.magic.BURN] = 25,
    [dsp.magic.FROST] = 25,
    [dsp.magic.CHOKE] = 25,
    [dsp.magic.RASP] = 25,
    [dsp.magic.SHOCK] = 25,
    [dsp.magic.DROWN] = 25,
    [dsp.magic.RETRACE] = 150,
    [dsp.magic.ABSORB_ACC] = 33,
    [dsp.magic.METEOR_II] = 666,
    [dsp.magic.DRAIN] = 21,
    [dsp.magic.DRAIN_II] = 37,
    [dsp.magic.ASPIR] = 10,
    [dsp.magic.ASPIR_II] = 5,
    [dsp.magic.BLAZE_SPIKES] = 8,
    [dsp.magic.ICE_SPIKES] = 16,
    [dsp.magic.SHOCK_SPIKES] = 24,
    [dsp.magic.STUN] = 25,
    [dsp.magic.SLEEP] = 19,
    [dsp.magic.BLIND] = 5,
    [dsp.magic.BREAK] = 39,
    [dsp.magic.VIRUS] = 39,
    [dsp.magic.CURSE] = 39,
    [dsp.magic.BIND] = 8,
    [dsp.magic.SLEEP_II] = 29,
    [dsp.magic.DISPEL] = 25,
    [dsp.magic.WARP] = 100,
    [dsp.magic.WARP_II] = 150,
    [dsp.magic.ESCAPE] = 125,
    [dsp.magic.TRACTOR] = 26,
    [dsp.magic.TRACTOR_II] = 50,
    [dsp.magic.ABSORB_STR] = 33,
    [dsp.magic.ABSORB_DEX] = 33,
    [dsp.magic.ABSORB_VIT] = 33,
    [dsp.magic.ABSORB_AGI] = 33,
    [dsp.magic.ABSORB_INT] = 33,
    [dsp.magic.ABSORB_MND] = 33,
    [dsp.magic.ABSORB_CHR] = 33,
    [dsp.magic.SLEEPGA] = 38,
    [dsp.magic.SLEEPGA_II] = 58,
    [dsp.magic.ABSORB_TP] = 33,
    [dsp.magic.BLIND_II] = 31,
    [dsp.magic.DREAD_SPIKES] = 78,
    [dsp.magic.GEOHELIX] = 26,
    [dsp.magic.HYDROHELIX] = 26,
    [dsp.magic.ANEMOHELIX] = 26,
    [dsp.magic.PYROHELIX] = 26,
    [dsp.magic.CRYOHELIX] = 26,
    [dsp.magic.IONOHELIX] = 26,
    [dsp.magic.NOCTOHELIX] = 26,
    [dsp.magic.LUMINOHELIX] = 26,
    [dsp.magic.ADDLE] = 36,
    [dsp.magic.KLIMAFORM] = 30,
    [dsp.magic.ANIMUS_AUGEO] = 21,
    [dsp.magic.ANIMUS_MINUO] = 21,
    [dsp.magic.ENLIGHT] = 24,
    [dsp.magic.ENDARK] = 24,
    [dsp.magic.ENFIRE_II] = 24,
    [dsp.magic.ENBLIZZARD_II] = 24,
    [dsp.magic.ENAERO_II] = 24,
    [dsp.magic.ENSTONE_II] = 24,
    [dsp.magic.ENTHUNDER_II] = 24,
    [dsp.magic.ENWATER_II] = 24,
    [dsp.magic.MONOMI_ICHI] = 2553,
    [dsp.magic.AISHA_ICHI] = 2555,
    [dsp.magic.KATON_ICHI] = 1161,
    [dsp.magic.KATON_NI] = 1161,
    [dsp.magic.KATON_SAN] = 1161,
    [dsp.magic.HYOTON_ICHI] = 1164,
    [dsp.magic.HYOTON_NI] = 1164,
    [dsp.magic.HYOTON_SAN] = 1164,
    [dsp.magic.HUTON_ICHI] = 1167,
    [dsp.magic.HUTON_NI] = 1167,
    [dsp.magic.HUTON_SAN] = 1167,
    [dsp.magic.DOTON_ICHI] = 1170,
    [dsp.magic.DOTON_NI] = 1170,
    [dsp.magic.DOTON_SAN] = 1170,
    [dsp.magic.RAITON_ICHI] = 1173,
    [dsp.magic.RAITON_NI] = 1173,
    [dsp.magic.RAITON_SAN] = 1173,
    [dsp.magic.SUITON_ICHI] = 1176,
    [dsp.magic.SUITON_NI] = 1176,
    [dsp.magic.SUITON_SAN] = 1176,
    [dsp.magic.UTSUSEMI_ICHI] = 1179,
    [dsp.magic.UTSUSEMI_NI] = 1179,
    [dsp.magic.UTSUSEMI_SAN] = 1179,
    [dsp.magic.JUBAKU_ICHI] = 1182,
    [dsp.magic.JUBAKU_NI] = 1182,
    [dsp.magic.JUBAKU_SAN] = 1182,
    [dsp.magic.HOJO_ICHI] = 1185,
    [dsp.magic.HOJO_NI] = 1185,
    [dsp.magic.HOJO_SAN] = 1185,
    [dsp.magic.KURAYAMI_ICHI] = 1188,
    [dsp.magic.KURAYAMI_NI] = 1188,
    [dsp.magic.KURAYAMI_SAN] = 1188,
    [dsp.magic.DOKUMORI_ICHI] = 1191,
    [dsp.magic.DOKUMORI_NI] = 1191,
    [dsp.magic.DOKUMORI_SAN] = 1191,
    [dsp.magic.TONKO_ICHI] = 1194,
    [dsp.magic.TONKO_NI] = 1194,
    [dsp.magic.TONKO_SAN] = 1194,
    [dsp.magic.PARALYGA] = 12,
    [dsp.magic.SLOWGA] = 30,
    [dsp.magic.HASTEGA] = 80,
    [dsp.magic.SILENCEGA] = 32,
    [dsp.magic.DISPELGA] = 20,
    [dsp.magic.BLINDGA] = 10,
    [dsp.magic.BINDGA] = 16,
    [dsp.magic.BREAKGA] = 100,
    [dsp.magic.GRAVIGA] = 48,
    [dsp.magic.DEATH] = 666,
    [dsp.magic.REFRESH_II] = 60,
    [dsp.magic.CURA_II] = 45,
    [dsp.magic.CURA_III] = 60,
    [dsp.magic.REGEN_IV] = 82,
    [dsp.magic.EMBRAVA] = 1,
    [dsp.magic.BOOST_STR] = 36,
    [dsp.magic.BOOST_DEX] = 36,
    [dsp.magic.BOOST_VIT] = 36,
    [dsp.magic.BOOST_AGI] = 36,
    [dsp.magic.BOOST_INT] = 36,
    [dsp.magic.BOOST_MND] = 36,
    [dsp.magic.BOOST_CHR] = 36,
    [dsp.magic.GAIN_STR] = 36,
    [dsp.magic.GAIN_DEX] = 36,
    [dsp.magic.GAIN_VIT] = 36,
    [dsp.magic.GAIN_AGI] = 36,
    [dsp.magic.GAIN_INT] = 36,
    [dsp.magic.GAIN_MND] = 36,
    [dsp.magic.GAIN_CHR] = 36,
    [dsp.magic.TEMPER] = 36,
    [dsp.magic.ADLOQUIUM] = 50,
    [dsp.magic.FIRAJA] = 358,
    [dsp.magic.BLIZZAJA] = 378,
    [dsp.magic.AEROJA] = 338,
    [dsp.magic.STONEJA] = 298,
    [dsp.magic.THUNDAJA] = 398,
    [dsp.magic.WATERJA] = 318,
    [dsp.magic.KAUSTRA] = 1,
    [dsp.magic.IMPACT] = 666,
    [dsp.magic.REGEN_V] = 100,
    [dsp.magic.GEKKA_ICHI] = 8803,
    [dsp.magic.YAIN_ICHI] = 8804,
    [dsp.magic.MYOSHU_ICHI] = 2642,
    [dsp.magic.YURIN_ICHI] = 2643,
    [dsp.magic.KAKKA_ICHI] = 2644,
    [dsp.magic.MIGAWARI_ICHI] = 2970,
    [dsp.magic.HASTE_II] = 80,
    [dsp.magic.DISTRACT] = 32,
    [dsp.magic.DISTRACT_II] = 58,
    [dsp.magic.FRAZZLE] = 38,
    [dsp.magic.FRAZZLE_II] = 64,
    [dsp.magic.FLURRY] = 40,
    [dsp.magic.FLURRY_II] = 80,
}

-- magic name, {{effect flags}, shouldHaveFlag}
-- shouldHaveFlag set to true means the effects must be present, otherwise the effect must NOT be present
local magicEffectIndex = {
    [dsp.magic.CURE] = nil,
    [dsp.magic.CURE_II] = nil,
    [dsp.magic.CURE_III] = nil,
    [dsp.magic.CURE_IV] = nil,
    [dsp.magic.CURE_V] = nil,
    [dsp.magic.CURE_VI] = nil,
    [dsp.magic.CURAGA] = nil,
    [dsp.magic.CURAGA_II] = nil,
    [dsp.magic.CURAGA_III] = nil,
    [dsp.magic.CURAGA_IV] = nil,
    [dsp.magic.CURAGA_V] = nil,
    [dsp.magic.RAISE] = {[{dsp.effect.KO}] = true},
    [dsp.magic.RAISE_II] = {[{dsp.effect.KO}] = true},
    [dsp.magic.POISONA] = {[{dsp.effect.POISON}] = true},
    [dsp.magic.PARALYNA] = {[{dsp.effect.PARALYSIS}] = true},
    [dsp.magic.BLINDNA] = {[{dsp.effect.BLINDNESS}] = true},
    [dsp.magic.SILENA] = {[{dsp.effect.SILENCE}] = true},
    [dsp.magic.STONA] = {[{dsp.effect.PETRIFICATION}] = true},
    [dsp.magic.VIRUNA] = {[{dsp.effect.DISEASE, dsp.effect.PLAGUE}] = true},
    [dsp.magic.CURSNA] = {[{dsp.effect.CURSE_I, dsp.effect.CURSE_II}] = true},
    [dsp.magic.HOLY] = nil,
    [dsp.magic.HOLY_II] = nil,
    [dsp.magic.DIA] = {[{dsp.effect.DIA}] = false},
    [dsp.magic.DIA_II] = {[{dsp.effect.DIA}] = false},
    [dsp.magic.DIA_III] = {[{dsp.effect.DIA}] = false},
    [dsp.magic.DIA_IV] = {[{dsp.effect.DIA}] = false},
    [dsp.magic.DIA_V] = {[{dsp.effect.DIA}] = false},
    [dsp.magic.BANISH] = nil,
    [dsp.magic.BANISH_II] = nil,
    [dsp.magic.BANISH_III] = nil,
    [dsp.magic.BANISH_IV] = nil,
    [dsp.magic.BANISH_V] = nil,
    [dsp.magic.DIAGA] = {[{dsp.effect.DIA}] = false},
    [dsp.magic.DIAGA_II] = {[{dsp.effect.DIA}] = false},
    [dsp.magic.DIAGA_III] = {[{dsp.effect.DIA}] = false},
    [dsp.magic.DIAGA_IV] = {[{dsp.effect.DIA}] = false},
    [dsp.magic.DIAGA_V] = {[{dsp.effect.DIA}] = false},
    [dsp.magic.BANISHGA] = nil,
    [dsp.magic.BANISHGA_II] = nil,
    [dsp.magic.BANISHGA_III] = nil,
    [dsp.magic.BANISHGA_IV] = nil,
    [dsp.magic.BANISHGA_V] = nil,
    [dsp.magic.PROTECT] = {[{dsp.effect.PROTECT}] = false},
    [dsp.magic.PROTECT_II] = {[{dsp.effect.PROTECT}] = false},
    [dsp.magic.PROTECT_III] = {[{dsp.effect.PROTECT}] = false},
    [dsp.magic.PROTECT_IV] = {[{dsp.effect.PROTECT}] = false},
    [dsp.magic.PROTECT_V] = {[{dsp.effect.PROTECT}] = false},
    [dsp.magic.SHELL] = {[{dsp.effect.SHELL}] = false},
    [dsp.magic.SHELL_II] = {[{dsp.effect.SHELL}] = false},
    [dsp.magic.SHELL_III] = {[{dsp.effect.SHELL}] = false},
    [dsp.magic.SHELL_IV] = {[{dsp.effect.SHELL}] = false},
    [dsp.magic.SHELL_V] = {[{dsp.effect.SHELL}] = false},
    [dsp.magic.BLINK] = {[{dsp.effect.BLINK}] = false},
    [dsp.magic.STONESKIN] = {[{dsp.effect.STONESKIN}] = false},
    [dsp.magic.AQUAVEIL] = {[{dsp.effect.AQUAVEIL}] = false},
    [dsp.magic.SLOW] = {[{dsp.effect.SLOW}] = false},
    [dsp.magic.HASTE] = {[{dsp.effect.HASTE}] = false},
    [dsp.magic.PARALYZE] = {[{dsp.effect.PARALYSIS}] = false},
    [dsp.magic.SILENCE] = {[{dsp.effect.SILENCE}] = false},
    [dsp.magic.BARFIRE] = {[{dsp.effect.BARFIRE}] = false},
    [dsp.magic.BARBLIZZARD] = {[{dsp.effect.BARBLIZZARD}] = false},
    [dsp.magic.BARAERO] = {[{dsp.effect.BARAERO}] = false},
    [dsp.magic.BARSTONE] = {[{dsp.effect.BARSTONE}] = false},
    [dsp.magic.BARTHUNDER] = {[{dsp.effect.BARTHUNDER}] = false},
    [dsp.magic.BARWATER] = {[{dsp.effect.BARWATER}] = false},
    [dsp.magic.BARFIRA] = {[{dsp.effect.BARFIRE}] = false},
    [dsp.magic.BARBLIZZARA] = {[{dsp.effect.BARBLIZZARD}] = false},
    [dsp.magic.BARAERA] = {[{dsp.effect.BARAERO}] = false},
    [dsp.magic.BARSTONRA] = {[{dsp.effect.BARSTONE}] = false},
    [dsp.magic.BARTHUNDRA] = {[{dsp.effect.BARTHUNDER}] = false},
    [dsp.magic.BARWATERA] = {[{dsp.effect.BARWATER}] = false},
    [dsp.magic.BARSLEEP] = {[{dsp.effect.BARSLEEP}] = false},
    [dsp.magic.BARPOISON] = {[{dsp.effect.BARPOISON}] = false},
    [dsp.magic.BARPARALYZE] = {[{dsp.effect.BARPARALYZE}] = false},
    [dsp.magic.BARBLIND] = {[{dsp.effect.BARBLIND}] = false},
    [dsp.magic.BARSILENCE] = {[{dsp.effect.BARSILENCE}] = false},
    [dsp.magic.BARPETRIFY] = {[{dsp.effect.BARPETRIFY}] = false},
    [dsp.magic.BARVIRUS] = {[{dsp.effect.BARVIRUS}] = false},
    [dsp.magic.SLOW_II] = {[{dsp.effect.SLOW}] = false},
    [dsp.magic.PARALYZE_II] = {[{dsp.effect.PARALYSIS}] = false},
    [dsp.magic.RECALL_JUGNER] = nil,
    [dsp.magic.RECALL_PASHH] = nil,
    [dsp.magic.RECALL_MERIPH] = nil,
    [dsp.magic.BARAMNESIA] = {[{dsp.effect.BARAMNESIA}] = false},
    [dsp.magic.BARAMNESRA] = {[{dsp.effect.BARAMNESIA}] = false},
    [dsp.magic.BARSLEEPRA] = {[{dsp.effect.BARSLEEP}] = false},
    [dsp.magic.BARPOISONRA] = {[{dsp.effect.BARPOISON}] = false},
    [dsp.magic.BARPARALYZRA] = {[{dsp.effect.BARPARALYZE}] = false},
    [dsp.magic.BARBLINDRA] = {[{dsp.effect.BARBLIND}] = false},
    [dsp.magic.BARSILENCERA] = {[{dsp.effect.BARSILENCE}] = false},
    [dsp.magic.BARPETRA] = {[{dsp.effect.BARPETRIFY}] = false},
    [dsp.magic.BARVIRA] = {[{dsp.effect.BARVIRUS}] = false},
    [dsp.magic.CURA] = nil,
    [dsp.magic.SACRIFICE] = nil,
    [dsp.magic.ESUNA] = nil,
    [dsp.magic.AUSPICE] = nil,
    [dsp.magic.REPRISAL] = nil,
    [dsp.magic.REPOSE] = nil,
    [dsp.magic.SANDSTORM] = nil,
    [dsp.magic.ENFIRE] = nil,
    [dsp.magic.ENBLIZZARD] = nil,
    [dsp.magic.ENAERO] = nil,
    [dsp.magic.ENSTONE] = nil,
    [dsp.magic.ENTHUNDER] = nil,
    [dsp.magic.ENWATER] = nil,
    [dsp.magic.PHALANX] = {[{dsp.effect.PHALANX}] = false},
    [dsp.magic.PHALANX_II] = {[{dsp.effect.PHALANX}] = false},
    [dsp.magic.REGEN] = {[{dsp.effect.REGEN}] = false},
    [dsp.magic.REFRESH] = {[{dsp.effect.REFRESH}] = false},
    [dsp.magic.REGEN_II] = {[{dsp.effect.REGEN}] = false},
    [dsp.magic.REGEN_III] = nil,
    [dsp.magic.FLASH] = {[{dsp.effect.FLASH}] = false},
    [dsp.magic.RAINSTORM] = nil,
    [dsp.magic.WINDSTORM] = nil,
    [dsp.magic.FIRESTORM] = nil,
    [dsp.magic.HAILSTORM] = nil,
    [dsp.magic.THUNDERSTORM] = nil,
    [dsp.magic.VOIDSTORM] = nil,
    [dsp.magic.AURORASTORM] = nil,
    [dsp.magic.TELEPORT_YHOAT] = nil,
    [dsp.magic.TELEPORT_ALTEP] = nil,
    [dsp.magic.TELEPORT_HOLLA] = nil,
    [dsp.magic.TELEPORT_DEM] = nil,
    [dsp.magic.TELEPORT_MEA] = nil,
    [dsp.magic.PROTECTRA] = {[{dsp.effect.PROTECT}] = false},
    [dsp.magic.PROTECTRA_II] = {[{dsp.effect.PROTECT}] = false},
    [dsp.magic.PROTECTRA_III] = {[{dsp.effect.PROTECT}] = false},
    [dsp.magic.PROTECTRA_IV] = {[{dsp.effect.PROTECT}] = false},
    [dsp.magic.PROTECTRA_V] = {[{dsp.effect.PROTECT}] = false},
    [dsp.magic.SHELLRA] = {[{dsp.effect.SHELL}] = false},
    [dsp.magic.SHELLRA_II] = {[{dsp.effect.SHELL}] = false},
    [dsp.magic.SHELLRA_III] = {[{dsp.effect.SHELL}] = false},
    [dsp.magic.SHELLRA_IV] = {[{dsp.effect.SHELL}] = false},
    [dsp.magic.SHELLRA_V] = {[{dsp.effect.SHELL}] = false},
    [dsp.magic.RERAISE] = nil,
    [dsp.magic.INVISIBLE] = nil,
    [dsp.magic.SNEAK] = nil,
    [dsp.magic.DEODORIZE] = nil,
    [dsp.magic.TELEPORT_VAHZL] = nil,
    [dsp.magic.RAISE_III] = nil,
    [dsp.magic.RERAISE_II] = nil,
    [dsp.magic.RERAISE_III] = nil,
    [dsp.magic.ERASE] = nil,
    [dsp.magic.FIRE] = nil,
    [dsp.magic.FIRE_II] = nil,
    [dsp.magic.FIRE_III] = nil,
    [dsp.magic.FIRE_IV] = nil,
    [dsp.magic.FIRE_V] = nil,
    [dsp.magic.BLIZZARD] = nil,
    [dsp.magic.BLIZZARD_II] = nil,
    [dsp.magic.BLIZZARD_III] = nil,
    [dsp.magic.BLIZZARD_IV] = nil,
    [dsp.magic.BLIZZARD_V] = nil,
    [dsp.magic.AERO] = nil,
    [dsp.magic.AERO_II] = nil,
    [dsp.magic.AERO_III] = nil,
    [dsp.magic.AERO_IV] = nil,
    [dsp.magic.AERO_V] = nil,
    [dsp.magic.STONE] = nil,
    [dsp.magic.STONE_II] = nil,
    [dsp.magic.STONE_III] = nil,
    [dsp.magic.STONE_IV] = nil,
    [dsp.magic.STONE_V] = nil,
    [dsp.magic.THUNDER] = nil,
    [dsp.magic.THUNDER_II] = nil,
    [dsp.magic.THUNDER_III] = nil,
    [dsp.magic.THUNDER_IV] = nil,
    [dsp.magic.THUNDER_V] = nil,
    [dsp.magic.WATER] = nil,
    [dsp.magic.WATER_II] = nil,
    [dsp.magic.WATER_III] = nil,
    [dsp.magic.WATER_IV] = nil,
    [dsp.magic.WATER_V] = nil,
    [dsp.magic.FIRAGA] = nil,
    [dsp.magic.FIRAGA_II] = nil,
    [dsp.magic.FIRAGA_III] = nil,
    [dsp.magic.FIRAGA_IV] = nil,
    [dsp.magic.FIRAGA_V] = nil,
    [dsp.magic.BLIZZAGA] = nil,
    [dsp.magic.BLIZZAGA_II] = nil,
    [dsp.magic.BLIZZAGA_III] = nil,
    [dsp.magic.BLIZZAGA_IV] = nil,
    [dsp.magic.BLIZZAGA_V] = nil,
    [dsp.magic.AEROGA] = nil,
    [dsp.magic.AEROGA_II] = nil,
    [dsp.magic.AEROGA_III] = nil,
    [dsp.magic.AEROGA_IV] = nil,
    [dsp.magic.AEROGA_V] = nil,
    [dsp.magic.STONEGA] = nil,
    [dsp.magic.STONEGA_II] = nil,
    [dsp.magic.STONEGA_III] = nil,
    [dsp.magic.STONEGA_IV] = nil,
    [dsp.magic.STONEGA_V] = nil,
    [dsp.magic.THUNDAGA] = nil,
    [dsp.magic.THUNDAGA_II] = nil,
    [dsp.magic.THUNDAGA_III] = nil,
    [dsp.magic.THUNDAGA_IV] = nil,
    [dsp.magic.THUNDAGA_V] = nil,
    [dsp.magic.WATERGA] = nil,
    [dsp.magic.WATERGA_II] = nil,
    [dsp.magic.WATERGA_III] = nil,
    [dsp.magic.WATERGA_IV] = nil,
    [dsp.magic.WATERGA_V] = nil,
    [dsp.magic.FLARE] = nil,
    [dsp.magic.FLARE_II] = nil,
    [dsp.magic.FREEZE] = nil,
    [dsp.magic.FREEZE_II] = nil,
    [dsp.magic.TORNADO] = nil,
    [dsp.magic.TORNADO_II] = nil,
    [dsp.magic.QUAKE] = nil,
    [dsp.magic.QUAKE_II] = nil,
    [dsp.magic.BURST] = nil,
    [dsp.magic.BURST_II] = nil,
    [dsp.magic.FLOOD] = nil,
    [dsp.magic.FLOOD_II] = nil,
    [dsp.magic.GRAVITY] = nil,
    [dsp.magic.GRAVITY_II] = nil,
    [dsp.magic.METEOR] = nil,
    [dsp.magic.COMET] = nil,
    [dsp.magic.POISON] = nil,
    [dsp.magic.POISON_II] = nil,
    [dsp.magic.POISON_III] = nil,
    [dsp.magic.POISON_IV] = nil,
    [dsp.magic.POISON_V] = nil,
    [dsp.magic.POISONGA] = nil,
    [dsp.magic.POISONGA_II] = nil,
    [dsp.magic.POISONGA_III] = nil,
    [dsp.magic.POISONGA_IV] = nil,
    [dsp.magic.POISONGA_V] = nil,
    [dsp.magic.BIO] = nil,
    [dsp.magic.BIO_II] = nil,
    [dsp.magic.BIO_III] = nil,
    [dsp.magic.BIO_IV] = nil,
    [dsp.magic.BIO_V] = nil,
    [dsp.magic.BURN] = nil,
    [dsp.magic.FROST] = nil,
    [dsp.magic.CHOKE] = nil,
    [dsp.magic.RASP] = nil,
    [dsp.magic.SHOCK] = nil,
    [dsp.magic.DROWN] = nil,
    [dsp.magic.RETRACE] = nil,
    [dsp.magic.ABSORB_ACC] = nil,
    [dsp.magic.METEOR_II] = nil,
    [dsp.magic.DRAIN] = nil,
    [dsp.magic.DRAIN_II] = nil,
    [dsp.magic.ASPIR] = nil,
    [dsp.magic.ASPIR_II] = nil,
    [dsp.magic.BLAZE_SPIKES] = nil,
    [dsp.magic.ICE_SPIKES] = nil,
    [dsp.magic.SHOCK_SPIKES] = nil,
    [dsp.magic.STUN] = nil,
    [dsp.magic.SLEEP] = {[{dsp.effect.SLEEP_I}] = false},
    [dsp.magic.BLIND] = {[{dsp.effect.BLINDNESS}] = false},
    [dsp.magic.BREAK] = nil,
    [dsp.magic.VIRUS] = nil,
    [dsp.magic.CURSE] = nil,
    [dsp.magic.BIND] = nil,
    [dsp.magic.SLEEP_II] = {[{dsp.effect.SLEEP_II}] = false},
    [dsp.magic.DISPEL] = nil,
    [dsp.magic.WARP] = nil,
    [dsp.magic.WARP_II] = nil,
    [dsp.magic.ESCAPE] = nil,
    [dsp.magic.TRACTOR] = nil,
    [dsp.magic.TRACTOR_II] = nil,
    [dsp.magic.ABSORB_STR] = nil,
    [dsp.magic.ABSORB_DEX] = nil,
    [dsp.magic.ABSORB_VIT] = nil,
    [dsp.magic.ABSORB_AGI] = nil,
    [dsp.magic.ABSORB_INT] = nil,
    [dsp.magic.ABSORB_MND] = nil,
    [dsp.magic.ABSORB_CHR] = nil,
    [dsp.magic.SLEEPGA] = nil,
    [dsp.magic.SLEEPGA_II] = nil,
    [dsp.magic.ABSORB_TP] = nil,
    [dsp.magic.BLIND_II] = nil,
    [dsp.magic.DREAD_SPIKES] = nil,
    [dsp.magic.GEOHELIX] = nil,
    [dsp.magic.HYDROHELIX] = nil,
    [dsp.magic.ANEMOHELIX] = nil,
    [dsp.magic.PYROHELIX] = nil,
    [dsp.magic.CRYOHELIX] = nil,
    [dsp.magic.IONOHELIX] = nil,
    [dsp.magic.NOCTOHELIX] = nil,
    [dsp.magic.LUMINOHELIX] = nil,
    [dsp.magic.ADDLE] = {[{dsp.effect.ADDLE}] = false},
    [dsp.magic.KLIMAFORM] = nil,
    [dsp.magic.ANIMUS_AUGEO] = nil,
    [dsp.magic.ANIMUS_MINUO] = nil,
    [dsp.magic.ENLIGHT] = nil,
    [dsp.magic.ENDARK] = nil,
    [dsp.magic.ENFIRE_II] = nil,
    [dsp.magic.ENBLIZZARD_II] = nil,
    [dsp.magic.ENAERO_II] = nil,
    [dsp.magic.ENSTONE_II] = nil,
    [dsp.magic.ENTHUNDER_II] = nil,
    [dsp.magic.ENWATER_II] = nil,
    [dsp.magic.MONOMI_ICHI] = nil,
    [dsp.magic.AISHA_ICHI] = nil,
    [dsp.magic.KATON_ICHI] = nil,
    [dsp.magic.KATON_NI] = nil,
    [dsp.magic.KATON_SAN] = nil,
    [dsp.magic.HYOTON_ICHI] = nil,
    [dsp.magic.HYOTON_NI] = nil,
    [dsp.magic.HYOTON_SAN] = nil,
    [dsp.magic.HUTON_ICHI] = nil,
    [dsp.magic.HUTON_NI] = nil,
    [dsp.magic.HUTON_SAN] = nil,
    [dsp.magic.DOTON_ICHI] = nil,
    [dsp.magic.DOTON_NI] = nil,
    [dsp.magic.DOTON_SAN] = nil,
    [dsp.magic.RAITON_ICHI] = nil,
    [dsp.magic.RAITON_NI] = nil,
    [dsp.magic.RAITON_SAN] = nil,
    [dsp.magic.SUITON_ICHI] = nil,
    [dsp.magic.SUITON_NI] = nil,
    [dsp.magic.SUITON_SAN] = nil,
    [dsp.magic.UTSUSEMI_ICHI] = nil,
    [dsp.magic.UTSUSEMI_NI] = nil,
    [dsp.magic.UTSUSEMI_SAN] = nil,
    [dsp.magic.JUBAKU_ICHI] = nil,
    [dsp.magic.JUBAKU_NI] = nil,
    [dsp.magic.JUBAKU_SAN] = nil,
    [dsp.magic.HOJO_ICHI] = nil,
    [dsp.magic.HOJO_NI] = nil,
    [dsp.magic.HOJO_SAN] = nil,
    [dsp.magic.KURAYAMI_ICHI] = nil,
    [dsp.magic.KURAYAMI_NI] = nil,
    [dsp.magic.KURAYAMI_SAN] = nil,
    [dsp.magic.DOKUMORI_ICHI] = nil,
    [dsp.magic.DOKUMORI_NI] = nil,
    [dsp.magic.DOKUMORI_SAN] = nil,
    [dsp.magic.TONKO_ICHI] = nil,
    [dsp.magic.TONKO_NI] = nil,
    [dsp.magic.TONKO_SAN] = nil,
    [dsp.magic.PARALYGA] = nil,
    [dsp.magic.SLOWGA] = nil,
    [dsp.magic.HASTEGA] = nil,
    [dsp.magic.SILENCEGA] = nil,
    [dsp.magic.DISPELGA] = nil,
    [dsp.magic.BLINDGA] = nil,
    [dsp.magic.BINDGA] = nil,
    [dsp.magic.BREAKGA] = nil,
    [dsp.magic.GRAVIGA] = nil,
    [dsp.magic.DEATH] = nil,
    [dsp.magic.REFRESH_II] = {[{dsp.effect.REFRESH}] = false},
    [dsp.magic.CURA_II] = nil,
    [dsp.magic.CURA_III] = nil,
    [dsp.magic.REGEN_IV] = nil,
    [dsp.magic.EMBRAVA] = nil,
    [dsp.magic.BOOST_STR] = nil,
    [dsp.magic.BOOST_DEX] = nil,
    [dsp.magic.BOOST_VIT] = nil,
    [dsp.magic.BOOST_AGI] = nil,
    [dsp.magic.BOOST_INT] = nil,
    [dsp.magic.BOOST_MND] = nil,
    [dsp.magic.BOOST_CHR] = nil,
    [dsp.magic.GAIN_STR] = nil,
    [dsp.magic.GAIN_DEX] = nil,
    [dsp.magic.GAIN_VIT] = nil,
    [dsp.magic.GAIN_AGI] = nil,
    [dsp.magic.GAIN_INT] = nil,
    [dsp.magic.GAIN_MND] = nil,
    [dsp.magic.GAIN_CHR] = nil,
    [dsp.magic.TEMPER] = nil,
    [dsp.magic.ADLOQUIUM] = nil,
    [dsp.magic.FIRAJA] = nil,
    [dsp.magic.BLIZZAJA] = nil,
    [dsp.magic.AEROJA] = nil,
    [dsp.magic.STONEJA] = nil,
    [dsp.magic.THUNDAJA] = nil,
    [dsp.magic.WATERJA] = nil,
    [dsp.magic.KAUSTRA] = nil,
    [dsp.magic.IMPACT] = nil,
    [dsp.magic.REGEN_V] = nil,
    [dsp.magic.GEKKA_ICHI] = nil,
    [dsp.magic.YAIN_ICHI] = nil,
    [dsp.magic.MYOSHU_ICHI] = nil,
    [dsp.magic.YURIN_ICHI] = nil,
    [dsp.magic.KAKKA_ICHI] = nil,
    [dsp.magic.MIGAWARI_ICHI] = nil,
    [dsp.magic.HASTE_II] = {[{dsp.effect.HASTE}] = false},
    [dsp.magic.DISTRACT] = nil,
    [dsp.magic.DISTRACT_II] = nil,
    [dsp.magic.FRAZZLE] = nil,
    [dsp.magic.FRAZZLE_II] = nil,
    [dsp.magic.FLURRY] = nil,
    [dsp.magic.FLURRY_II] = nil,
}

function isBuffAllowed(caster)
    return addDelay(caster, "buff", 7)
end

function isDebuffAllowed(caster)
    return addDelay(caster, "debuff", 15)
end

function isNukeAllowed(caster)
    return addDelay(caster, "nuke", 7)
end

function addDelay(caster, delayName, delayCooldown)
    local battletime = os.time()
    local delayTime = caster:getLocalVar(string.format("%sTime", delayName))

    if battletime > delayTime + delayCooldown then
        return true
    end

    return false
end

function tryBuffInOrder(caster, player, party, buffData)
    for index,value in ipairs(buffData) do
        local buff = value[1];
        local targetInfo = value[2];

        if (targetInfo / possibleBuffTargets.PLAYER) % 2 >= 1 then
            local didCast = doBuff(caster, player, buff)

            if didCast then return true end
        end

        if (targetInfo / possibleBuffTargets.CASTER) % 2 >= 1 then
            local didCast = doBuff(caster, caster, buff)

            if didCast then return true end
        end
        
        if (targetInfo / possibleBuffTargets.PARTY) % 2 >= 1 then
            local didCast = doPartyBuff(caster, party, buff)

            if didCast then return true end
        end
    end

    return false
end

function tryDebuffInOrder(caster, target, debuffList)
    for index,debuff in ipairs(debuffList) do
        local didCast = doDebuff(caster, target, debuff)

        if didCast then return true end
    end

    return false
end

function doPartyBuff(caster, party, buff)
    if magicGroupIndex[buff] ~= nil then
        doBuff(caster, caster, buff)
    end

    for i,member in pairs(party) do
        if doBuff(caster, member, buff) then return true end
    end

    return false;
end

function doCastSpell(caster, target, spell)
    local mp = caster:getMP()
    local doesTargetHaveEffectAlready = false

    if magicEffectIndex[spell] ~= nil then
        for effects,shouldEffectExist in pairs(magicEffectIndex[spell]) do
            for i,effect in pairs(effects) do
                doesTargetHaveEffectAlready = target:hasStatusEffect(effect)

                if (shouldEffectExist and (not doesTargetHaveEffectAlready)) or
                ((not shouldEffectExist) and doesTargetHaveEffectAlready) then
                    return false
                end
            end
        end
    end
    
    if caster:canUseSpell(spell) then
        local mpCost = magicIndex[spell]
        if mp >= mpCost then
            caster:castSpell(spell, target)
            return true;
        end
    end

    return false
end

function doBuff(caster, member, buff)
    if isBuffAllowed(caster) then
        local didCast = doCastSpell(caster, member, buff)

        if didCast then
            caster:setLocalVar("buffTime", os.time())
            return true;
        end
    end
 
    return false
end

function doDebuff(caster, target, debuff)
    if isDebuffAllowed(caster) then
        local didCast = doCastSpell(caster, target, debuff)

        if didCast then
            caster:setLocalVar("debuffTime", os.time())
            return true;
        end
    end
 
    return false
end

function getTableSize(t)
    local count = 0
    for _, __ in pairs(t) do
        count = count + 1
    end
    return count
end

function doNukeByTiers(caster, target, nukeTierData, shouldStopOnAggro)
    if shouldStopOnAggro and target:getTarget() == caster then
        return false
    end

    if isNukeAllowed(caster) then
        for index,value in ipairs(nukeTierData) do           
            local getSpellList = magicSingleTierIndex[value]
            local randomSpell = getSpellList[math.random(1, getTableSize(getSpellList))]

            local didCast = doCastSpell(caster, target, randomSpell)

            if didCast then
                caster:setLocalVar("nukeTime", os.time())
                return true
            end
        end
    end

    return false
end